### ISSUE TITLE
Webpack should be a peer dependency

### ISSUE THREAD

**Issue by vjpr** [geowarin/friendly-errors-webpack-plugin#64] opened 2018-03-22 15:06 UTC
https://github.com/geowarin/friendly-errors-webpack-plugin/blob/230d7615eacc7b42ab1386f6a560b9eb47776c0a/src/core/extractWebpackError.js#L4

**Comment by christophehurpeau** [comment] 2018-03-25 14:10
webpack is already a peer dependency: https://github.com/geowarin/friendly-errors-webpack-plugin/commit/ad55113be5239581aa809fa7dbd75091657125bb
Duplicate of #55

**Closed by christophehurpeau** 2018-03-25 14:10 UTC
